version: '3.7'

services:
  app:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - WEBPACKER_SERVER_HOST=${WEBPACKER_SERVER_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - GOOGLE_MAP_KEY=${GOOGLE_MAP_KEY}
  db:
    image: postgres:12
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
